### ISSUE TITLE
having ruiisue in run

### ISSUE THREAD

**Issue by MaxSamnani** [datocms/js-datocms-client#108]
> eslint ./ && npm run mocha

> datocms-client@3.4.3 mocha C:\laravel\js-datocms-client
> ACCOUNT_API_BASE_URL='https://account-api.datocms.com' SITE_API_BASE_URL='https://site-api.datocms.com' npm run inner:mocha

'ACCOUNT_API_BASE_URL' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! errno 1
npm ERR! datocms-client@3.4.3 mocha: `ACCOUNT_API_BASE_URL='https://account-api.datocms.com' SITE_API_BASE_URL='https://site-api.datocms.com' npm run inner:mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the datocms-client@3.4.3 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP Demo\AppData\Roaming\npm-cache\_logs\2021-04-07T15_12_14_795Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! datocms-client@3.4.3 test: `eslint ./ && npm run mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the datocms-client@3.4.3 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP Demo\AppData\Roaming\npm-cache\_logs\2021-04-07T15_12_14_881Z-debug.log
PS C:\laravel\js-datocms-client> npm run test

> datocms-client@3.4.3 test C:\laravel\js-datocms-client
> eslint ./ && npm run mocha

> datocms-client@3.4.3 mocha C:\laravel\js-datocms-client
> ACCOUNT_API_BASE_URL='https://account-api.datocms.com' SITE_API_BASE_URL='https://site-api.datocms.com' npm run inner:mocha

'ACCOUNT_API_BASE_URL' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! errno 1
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the datocms-client@3.4.3 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP Demo\AppData\Roaming\npm-cache\_logs\2021-04-07T15_21_24_570Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! datocms-client@3.4.3 test: `eslint ./ && npm run mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the datocms-client@3.4.3 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP Demo\AppData\Roaming\npm-cache\_logs\2021-04-07T15_21_24_632Z-debug.log
PS C:\laravel\js-datocms-client> npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.

**Comment by matjack1** [comment]
hey @MaxSamnani try getting rid of the env variables `ACCOUNT_API_BASE_URL='https://account-api.datocms.com' SITE_API_BASE_URL='https://site-api.datocms.com'` as they should be set as default for you. They are variables only for us to point at development/staging environments

**Comment by stefanoverna** [comment]
Please pull the latest version from master. We added `cross-env` to fix issues with ENV variables on Windows machines.
