### ISSUE TITLE
The application hangs at the end of some commands

### ISSUE THREAD

**Issue by janneronkko** [datocms/js-datocms-client#109]
I tried out migrations and was following https://www.datocms.com/docs/scripting-migrations/scripting-migrations-with-the-datocms-cli where the first example instructed me to run `dato new migration 'create article model'`

The command hanged after it had created the migration file. I tested versions 3.4.3, 3.4.2, 3.4.1, 3.4.0 and 3.3.0 and the command hanged with all 3.4 version but did not hang with 3.3.0

Also I noticed that `dato migrate --source=<src> --inPlace` also hangs at the end (without `--inPlace` it does not). With this I did not try different versions anymore.

Pressing ctrl+c does kill the application but that is not really an option, for example, in CI and is not nice even when you are running the command on terminal as you just don't know if everything was done.

**Comment by stefanoverna** [comment]
Thanks for reporting @janneronkko, it has been fixed in 3.4.4!
