### ISSUE TITLE
Binding to SIGINT prevented due to tmp module

### ISSUE THREAD

**Issue by benkitzelman** [datocms/js-datocms-client#112]
Hi,

Currently binding to `process.on("SIGINT", () => {});` is broken, due to the dependence on tmp v 0.1.0 (see https://github.com/raszi/node-tmp/issues/247).

Unfortunately, this is currently preventing us from gracefully shutting down our server as our signal trap is not being bound / being clobbered by tmp.

Any chance of bumping the version? 
Thanks

**Comment by benkitzelman** [comment]
PR: https://github.com/datocms/js-datocms-client/pull/113

**Comment by stefanoverna** [comment]
Thanks @benkitzelman, released as v3.4.7!
