### ISSUE TITLE
Parse ApiException errors to use in our code

### ISSUE THREAD

**Issue by andresgutgon** [datocms/js-datocms-client#115]
## What?
Hi, maybe there is a more efficient way of doing this. I'm debugging the request and don't find something better : )

## What we want?
We want to use DatoCMS validations and massage the error to show it translated in our UI. For example imagine we have an `email` field in a DatoCMS model. What we want is to tell the user that the field `email` is `required` and must have an email format.
We could go field by field and add validations on our side. But I though that would be great if we can take advantadge of DatoCMS models' validations. Like we can do on a Rails app for example.

### What are we trying?

When you debug and get a DatoCMS `ApiException` this is what you see. As you can see `error.message` is an string even if `details` is a valid JSON payload.
``` javascript
error.message
"422 MISSING_FIELDS (details: {\"required_fields\":[\"email\"],\"missing_fields\":[\"email\"]})"
```

I don't see anything else in `error` object for an `ApiException` 
What I'm doing for now is using a regexp to extract all the info we want in JSON format like this:
``` javascript
const matches = error.message.match(/(?<statusCode>\d+)+\s(?<errorCode>\w+)\s\(details\:\s(?<errors>[^\)]*)/)
const errors = JSON.parse(matches.groups.errors)
```

This give us the errors:
![image](https://user-images.githubusercontent.com/49499/117290279-e5806f80-ae6d-11eb-9d08-43da4194e754.png)

I feel this could be done by this client but as I said maybe is possible and I don't know how to use it

Thanks!

**Comment by andresgutgon** [comment]
Maybe exposing this would be nice https://github.com/datocms/js-datocms-client/blob/8df86e5cfd160922fc80c7dd6810fe853265dd2e/src/ApiException.js#L14 ?

**Comment by stefanoverna** [comment]
Sure, we could expose both error.attributes.details and error.attributes.code. If you've time please submit a MR, or I'll try to do it myself when I can free myself :)

**Comment by andresgutgon** [comment]
Let me check : )

**Comment by andresgutgon** [comment]
Yes! I can work with this

![image](https://user-images.githubusercontent.com/49499/117464999-82680900-af51-11eb-9da4-fab976e9f67d.png)

**Comment by stefanoverna** [comment]
Are you sure? `data` should definitely be an array! See this line, were we take the first error:

https://github.com/datocms/js-datocms-client/blob/8df86e5cfd160922fc80c7dd6810fe853265dd2e/src/ApiException.js#L13

**Comment by andresgutgon** [comment]
I think because the keys are numbers:
![image](https://user-images.githubusercontent.com/49499/117473623-73398900-af5a-11eb-9630-27cc78db499f.png)

**Comment by andresgutgon** [comment]
@stefanoverna do you know where I can find the documentation to know what types of error codes the API can return:

So far I have seen `MISSING_FIELDS` and `INVALID_FIELD`. Is a bit weird because `MISSING_FIELDS` returns an array of fields and `INVALID_FIELD` is information only for one field. 

Would be nicer to return always `INVALID_FIELD` and inside `details.code` to be `MISSING_FIELD`


Any way if you can point to the API error list would be more than enough 😄

**Comment by stefanoverna** [comment]
Iterating over `body.data` works for me:

```js
  try {
          await client.items.create({
            wrongFieldName: 'My first blog post',
            itemType: itemType.id,
          });
        } catch (e) {
          e.body.data.forEach(x => {
            console.log(x);
          })
        }
```

We don't have an official list of errors as they might change in the future, but:

* `INVALID_ATTRIBUTES`: when non-existing fields are passed
* `INVALID_FIELD`: format/validation fails over some field
* `MISSING_FIELDS`: when you need to pass some extra fields in the payload
* `INVALID_TYPE`: when you specify an invalid item type
* `DUPLICATE_SINGLETON`: when you try to create a single-instance record, but it already exists
* For tree-like collections:`INVALID_POSITION` and `INVALID_PARENT_ID`
* `INVALID_DATE` when setting `meta.created_at` and `meta.first_published_at` with wrong format

**Comment by andresgutgon** [comment]
> Iterating over body.data works for me:

I was using `body.each`. I guess an Object doesn't have `each`. My bad
