### ISSUE TITLE
Types not found

### ISSUE THREAD

**Issue by rodrigodiasf1984** [datocms/js-datocms-client#118]
Hello, I tried to install with npm and yarn, none of them is working! Can you help, please? 

yarn add -D @types/datocms-client     
yarn add v1.22.10
warning ../../../package.json: No license field
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2fdatocms-client: Not found".

npm i --save-dev @types/datocms-client
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fdatocms-client - Not found
npm ERR! 404 
npm ERR! 404  '@types/datocms-client@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

Grazie mille!

**Comment by stefanoverna** [comment]
Hey rodrigo, that's simply because TS types are not available for this package (yet)

**Comment by rodrigodiasf1984** [comment]
Hi Estefano, Ok  Grazie!
