### ISSUE TITLE
Error with Wordpress Importer

### ISSUE THREAD

**Issue by cbaxter713** [datocms/js-datocms-client#120]
I am trying to use the Wordpress Importer from the datocms-client package.  I have followed the directions in this article (https://www.datocms.com/blog/wordpress-importer).  I have ensured that the dato full access api token, wordress URL, wordpress username and password are all correct, and that the wordpress user has admin access.  But I keep getting the same error after running the command.  See screenshot for details.  

My terminal/machine is on node v12.22.3 and npm v6.14.13

Any help with this would be much appreciated.  We are trying to migrate the wordpress blog for a large client and having this import feature was a major reason we chose this path.

<img width="651" alt="Screen Shot 2021-09-23 at 12 03 38 PM" src="https://user-images.githubusercontent.com/6816493/134561222-7a604785-23cb-4123-970b-f6d43e5f67d5.png">

**Comment by matjack1** [comment]
hello @cbaxter713 I'm following up on support as I think it's a problem of your WP instance.
