### ISSUE TITLE
realFetch.call is not a function

### ISSUE THREAD

**Issue by joernroeder** [datocms/js-datocms-client#125]
I'm running into a [seemingly know](https://github.com/matthew-andrews/isomorphic-fetch/issues/194) issue when using the dato client inside a [gatsby function](https://www.gatsbyjs.com/docs/reference/functions/getting-started/#hello-world)

I'm not only seeing it on gatsby cloud but also in my local environment and the reason for that seems to be https://github.com/matthew-andrews/isomorphic-fetch/issues/194#issuecomment-737132024. There is also a potential simple fix around for some while https://github.com/matthew-andrews/isomorphic-fetch/pull/195 but the approach users are taking currently is using https://www.npmjs.com/package/cross-fetch instead.

```
// src/api/hello-get-upload-url.js

import { SiteClient } from "datocms-client"

const client = new SiteClient(process.env.DATO_CMS_TOKEN)

export default function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).send()
  }

  // request a new upload url
  client.uploadRequest.create({
    filename: 'foo.jpg',
  }).then((uploadRequest) => {
    console.log(uploadRequest);
    res.status(200).json(uploadRequest);
  })
  .catch((error) => {
    console.error(error);
    res.status(400).send();
  });
}
```

**Comment by stefanoverna** [comment]
Please try with 3.5.9 which uses cross-fetch! Thanks for reporting @joernroeder!
