### ISSUE TITLE
DATO_MANAGEMENT_API_TOKEN vs. DATO_API_TOKEN

### ISSUE THREAD

**Issue by moritzjacobs** [datocms/js-datocms-client#128]
The client seems to look for `DATO_MANAGEMENT_API_TOKEN` while the `dato check` command adds the `DATO_API_TOKEN` to the `.env`.

Is there a difference I don't understand or is this a bug? If it is, I can provide a PR, if you want.

Thanks for your help!

**Comment by stefanoverna** [comment]
There's a reason for that: DATO_API_TOKEN is meant to be a token with reduced priviledges, to be used with `dato check` and `dato dump`. DATO_MANAGEMENT_API_TOKEN is for all the management commands (environments, etc.)

**Comment by moritzjacobs** [comment]
Ah, I see.
