### ISSUE TITLE
Contentful importer: Clarify that this is a destructive/dangerous operation

### ISSUE THREAD

**Issue by arcataroger** [datocms/js-datocms-client#131]
Following [the instructions on this DatoCMS help page about Contentful imports](https://www.datocms.com/docs/import-and-export/import-space-from-contentful), I ran this program to import a particular Contentful model over to Dato.

It was **not** clear that this operation will destroy many things in Dato:

- Unused DatoCMS assets (i.e., it could clear your whole media library)
- Unused DatoCMS locales
- Any models of the same name as what's being imported

There was no warning of this either on the help page or in the script itself. Had I not run it against a sandbox environment first, we would've lost a lot of files.

Ideally, I think this importer should failsafe to leaving unused things alone instead of deleting them. Deletion could be an optional parameter, not the default behavior. And in the case of overrides, it should prompt you: "A model named _____ is already in this DatoCMS environment. Do you wish to overwrite it, rename the new model, or skip this model?"

Alternatively, a simpler workaround would be to at least warn the user when they run this CLI tool: "WARNING: This import will destroy ALL unused assets in DatoCMS (1,542 files) and locales (3), along with the following models: _____, ______, ______. Type CONTINUE to confirm."

**Comment by stefanoverna** [comment]
Agreed. We'll work on it real soon

**Comment by arcataroger** [comment]
Awesome, thank you!

**Comment by marcelofinamorvieira** [comment]
Added with v. 3.5.12
Thanks once again @arcataroger for the feed back!
