### ISSUE TITLE
Dato CLI gets stuck if colors 1.4.1, 1.4.2 or 1.4.44-liberty-2 is installed

### ISSUE THREAD

**Issue by janneronkko** [datocms/js-datocms-client#132]
i.e. Dato CLI is affected by https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/

You can work around the issue by installing version 1.4.0

To replicate the issue, just run *npm install datocms-client* and run *dato*

**Comment by thebuilder** [comment]
Seems like the library is only used in [two places](https://github.com/datocms/js-datocms-client/search?q=colors) - The best approach might be to replace the package with a safer package like [chalk](https://github.com/chalk/chalk).

**Comment by janneronkko** [comment]
Maybe a quick fix would be to release new version that masks newer versions of colors so that people installing latest datocms-client would not have issues

**Comment by stefanoverna** [comment]
Released as 3.5.13! Thank you all!
