### ISSUE TITLE
receiving runtime error from renderRule 

### ISSUE THREAD

**Issue by massitashakori** [datocms/js-datocms-client#147]
Hi, I noticed since the datocms-client dependencies updated we are having an issue with the error below:
`Unhandled Runtime Error
TypeError: (0 , datocms_structured_text_generic_html_renderer__WEBPACK_IMPORTED_MODULE_1__.renderRule) is not a function`

tried to put datocms-client version back but apparently, there are more dependencies' versions changed. any thoughts?

**Comment by stefanoverna** [comment]
On newer releases you should import `renderNodeRule` instead of `renderRule`!
