### ISSUE TITLE
High Vulnerability because of https-proxy-agent

### ISSUE THREAD

**Issue by dbismut** [datocms/js-datocms-client#16]
Hi, running `npm audit` on my project resulted in the following vulnerability:
- **[High]**: Denial of service from the package `https-proxy-agent`.

<img width="570" alt="vulnerability" src="https://user-images.githubusercontent.com/5003380/40231290-e3d6b7fe-5a9a-11e8-8f69-954e94eaf155.png">

Maybe you should try upgrading the package to its latest version?

**Comment by dbismut** [comment]
Also, upgrading `request` to its latest version makes the number of vulnerabilities drop from 17 to 5. In general there doesn't seem to be any semver implementation of the dependencies in package.json, I'm wondering why.

**Comment by stefanoverna** [comment]
Just updated dependencies, thanks! Also, we've added semversioning of dependencies.
