### ISSUE TITLE
Created records with an id of "null" and null itemType of "null" using Content Management API

### ISSUE THREAD

**Issue by anthonysapp** [datocms/js-datocms-client#28]
Using the API, I forgot to specify an itemType when creating a record. This seems to have created several records with ids of "null" and itemTypes of "null". I can't see them in the admin to delete them, or fetch / delete them using the js client because of their null ids.

**Comment by matjack1** [comment]
I cannot reproduce now, I'm getting

`Error: Required relationship: itemType`

But please if you can reproduce reopen the issue with a code example as this sounds important!

**Comment by anthonysapp** [comment]
I've got an open cms project with this issue - happy to chat via email about it or have you take a look at my project.

**Comment by matjack1** [comment]
Yes please! If you prefer just drop me a message at support@datocms.com and we can follow up there.

Thank you very much.
