### ISSUE TITLE
dump command: invalid json response body handling

### ISSUE THREAD

**Issue by gnuletik** [datocms/js-datocms-client#33]
Hi,

If the dump command fails for an HTTP error, it returns the exit code 0.
It would be really useful for CI if the dump command could return 1 in this case.

Here is an example usecase
```
✖ Fetching content from DatoCMS
  FetchError: invalid json response body at https://site-api.datocms.com/items?version=published&page%5Boffset%5D=300&page%5Blimit%5D=100 reason: Unexpected token < in JSON at position 0
  
  - body.js:48 
    [opo-gdpr]/[node-fetch]/lib/body.js:48:31

  - next_tick.js:189 process._tickCallback
    internal/process/next_tick.js:189:7
  
Done in 78.60s.
```

I can submit a PR. Any ideas how / where to implement that ?

My point is to implement some retry in case of error.
But maybe, it would be more accurate to implement the retry in this library.
It depends on the time we should wait before trying another request I guess.
What's your opinion on this?

Thanks

**Comment by matjack1** [comment]
Thank you for the suggestion! I've tried a solution in #36 :)
