### ISSUE TITLE
What types of param can I pass to uploadImage?

### ISSUE THREAD

**Issue by overkektus** [datocms/js-datocms-client#40]
I use lambda function and I want upload image in to datocms. But I receive image inside lambda function as multipart/form-data. How to upload a picture in this case?
`client.uploadImage('http://i.giphy.com/NXOF5rlaSXdAc.gif')`

**Comment by matjack1** [comment]
@overkektus can you maybe save the image locally and then pass the path to `uploadImage` ?

You can pass both a URL or a local path and they both work :)

**Comment by overkektus** [comment]
Thanks for answer!
