### ISSUE TITLE
Help: How to output multiple files fields to front matter

### ISSUE THREAD

**Issue by alexpi** [datocms/js-datocms-client#44]
I have this code that is generating .md files:
```javascript
module.exports = (dato, root) => {
  root.directory("content/projects", projectsDir => {
    dato.projects.forEach(project => {
      projectsDir.createPost(`${project.slug}.md`, "yaml", {
        frontmatter: {
          title: project.title,
          category: project.category.name,
          photos: project.photos.forEach(photo => {
            photo.url();
          })
        },
        content: project.content
      });
    });
  });
};
```
Everything works fine, except the photos front matter property that outpus null. I used the snippet that exists in the documentation https://www.datocms.com/docs/static-generators/other-ssg/fields#multiple-files-field

**Comment by matjack1** [comment]
hey @alexpi just checking that you are using the latest v2.0.4 of the client?

**Comment by alexpi** [comment]
I just updated and it is still not working. It works if I first build the array in a variable and use that for the front matter property.
```javascript
root.directory("content/projects", projectsDir => {
  dato.projects.forEach(project => {
    let photos = [];
    project.photos.forEach(photo => {
      photos.push(photo.url());
    });

    projectsDir.createPost(`${project.slug}.md`, "yaml", {
      frontmatter: {
        title: project.title,
        category: project.category.name,
        photos
      },
      content: project.content
    });
  });
});
```
I am not super experienced with javascript, maybe that was the right way to do it?

**Comment by matjack1** [comment]
I see! Try maybe like the first option, but replacing `forEach` with `map` ?

**Comment by alexpi** [comment]
Thanks, this is much cleaner.

**Comment by matjack1** [comment]
Great, I'm going to close this, but reopen if you need to :)
