### ISSUE TITLE
v3.0.6 wp-import doesn't work

### ISSUE THREAD

**Issue by clockshark** [datocms/js-datocms-client#51]
I still cannot import from WordPress.

it just hangs on importing data even from a brand new WordPress instance

$ ./node_modules/.bin/dato wp-import --token=token  --wpUrl=http://test.local/  --wpUser=user     --wpPassword=pass
√ Fetching existing data

**Comment by matjack1** [comment]
Hello @clockshark I've just tried to run a `wp-import` but I cannot reproduce :(

Can you please check if the JSON APIs are enabled by going to `http://test.loca/wp-json` ?

Can you help me reproduce otherwise?

Thanks!

**Comment by matjack1** [comment]
I've just seen all your messages in Support as well. Can you please confirm you are on the latest version by running `./node_modules/.bin/dato --version` ?

**Comment by clockshark** [comment]
http://test.local/wp-json?  yes this is working

Of course I am on the latest...thats why I said 306 in the title :)
$ ./node_modules/.bin/dato --version
3.0.6

I made it publicly accessible if you want to try it.  Its just a dev environ machine
http://3c96e6e7.ngrok.io/wp-json

username username  password password

I also tried in WSL, powershell and gitbash in both admin and non admin (sudo)

It just locks up after it gets the checkmark

**Comment by matjack1** [comment]
OK, on which operating system, node version are you?

**Comment by clockshark** [comment]
windows 10 

$ node -v
v10.15.3

**Comment by matjack1** [comment]
OK, I'll test it with that setup myself and get back to you, it might happen tomorrow though, hope it's OK

**Comment by matjack1** [comment]
yes, sure, thank you

**Comment by matjack1** [comment]
OK @clockshark we have tested v3.0.7 on Windows, Mac and Linux, it should work as expected.

Can you please try again and reopen the issue if needed? Thank you!
