### ISSUE TITLE
crashing dump

### ISSUE THREAD

**Issue by distinctperspective** [datocms/js-datocms-client#54]
crashing on this creat post loop

    root.directory('./_posts', dir => {
        dato.posts.forEach(post => {
            dir.createPost(
            `${post.slug}.md`,
            'yaml',
            {
                frontmatter: {
                title: post.title,
                featureimage: post.featureimage && post.featureimage.toMap(),
                permalink: `/blog/${post.slug}`,
                author: post.author && post.author.toMap(),
                excerpt: post.excerpt,
                layout: "blog-page",
                categories:  post.category.map(tag => tag.title),
                date: post.date,
                seo_meta_tags: post.seo

                },
                content: post.body
            }
            );
        });
    });

\ Writing content
<--- Last few GCs --->

[10712:0000024753D4E7A0]   116879 ms: Scavenge 1378.4 (1434.3) -> 1363.3 (1436.3) MB, 3.2 / 0.0 ms  (average mu = 0.282, current mu = 0.213) allocation failure 
[10712:0000024753D4E7A0]   116903 ms: Scavenge 1378.7 (1436.3) -> 1363.6 (1438.8) MB, 3.0 / 0.0 ms  (average mu = 0.282, current mu = 0.213) allocation failure 
[10712:0000024753D4E7A0]   116925 ms: Scavenge 1379.0 (1438.8) -> 1363.9 (1440.8) MB, 3.1 / 0.0 ms  (average mu = 0.282, current mu = 0.213) allocation failure 

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000003240515C5C1]
Security context: 0x02375da9e6e9 <JSObject>
    1: walker [000000F7DD1C2BE9] [C:\Users\dthre\Documents\GitHub\eleventy-dev\node_modules\traverse\index.js:~116] [pc=00000324051D389D](this=0x02c00808d5e1 <JSGlobal Object>,node_=0x02375daccfc1 <String[5]: field>)
    2: /* anonymous */ [000000397BE3B6F9] [C:\Users\dthre\Documents\GitHub\eleventy-dev\node_modules\traverse\index.js:~203] [pc=000003240516...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF73722F04A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+5114
 2: 00007FF73720A0C6 node::MakeCallback+4518
 3: 00007FF73720AA30 node_module_register+2032
 4: 00007FF7374920EE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF73749201F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF7379B2BC4 v8::internal::Heap::MaxHeapGrowingFactor+9556
 7: 00007FF7379A9C46 v8::internal::ScavengeJob::operator=+24310
 8: 00007FF7379A829C v8::internal::ScavengeJob::operator=+17740
 9: 00007FF7379B0F87 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF7379B1006 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF73756CDB7 v8::internal::Factory::NewFillerObject+55
12: 00007FF737602CC6 v8::internal::WasmJs::Install+29414
13: 000003240515C5C1

**Comment by matjack1** [comment]
@distinctperspective can you please share more details on your setup, like Node.JS version and also how did you install Node so that I can try reproducing?

If you are on a different version, can you please try using Node v10.x? I think I still need to test v12 on Windows :(

**Comment by matjack1** [comment]
Closing for lack of reply.
