### ISSUE TITLE
when I give wp-import command, docopt exits without any error

### ISSUE THREAD

**Issue by fatihky** [datocms/js-datocms-client#56]
Hi, I'm trying to import data from an existing wordpress site with your client. I've used the same command (changed the credentials) from your blog post: https://www.datocms.com/blog/wordpress-importer/ But the tools exits with a non-zero exit code at the https://github.com/datocms/js-datocms-client/blob/c98f547436ee254e79a7fdfdf0eff2f0a7d49254/src/cli.js#L21

I'm not sure what is the problem is, I don't know how do I extract some debug information from `doctop` module. My purpose is to let you know about this problem.

I've temporarily set up `minimist` for argument parsing. For anyone researching for a quick workaround, here it is:
```js
/// src/cli.js
/// please comment out or delete if (...) lines in code..
const argv = require('minimist')(process.argv.slice(2))

if (argv._[0] === 'dump') {
  dump(argv);
} else if (argv._[0] === 'check') {
  check(argv);
} else if (argv._[0] === 'wp-import') {
  const {
    token,
    wpUrl,
    wpUser,
    wpPassword,
  } = argv;

  wpImport(token, wpUrl, wpUser, wpPassword);
} else if (argv._[0] === 'contentful-import') {
  const {
    '--contentfulToken': contentfulToken,
    '--contentfulSpaceId': contentfulSpaceId,
    '--datoCmsToken': datoCmsToken,
    '--skipContent': skipContent,
  } = options;

  contentfulImport(
    contentfulToken,
    contentfulSpaceId,
    datoCmsToken,
    skipContent,
  );
}
```

**Comment by matjack1** [comment]
hey @fatihky thank you for reporting this!

We cannot replicate this, can you please specify your system setting? Like operating system and node.js version?

Thank you!

**Comment by fatihky** [comment]
Hi, maybe the special characters in the wordpress password caused this problem... When I put `--wpPassword` option in single quotes, command runs without a problem.

**Comment by matjack1** [comment]
Thank you for the feedback!
