### ISSUE TITLE
key spelling issue: appeareance

### ISSUE THREAD

**Issue by tbrannam** [datocms/js-datocms-client#60]
When writing migration scripts I was initially confused why my field definitions were not initialized as expected - it turned out that I had mistyped the `appeareance` for a field as `appearance`.  

Unless this is a British English variant that I am unfamiliar with, I think this is a misspelling of `appearance`.   It is found in this form throughout the DatoCms client and gatsby-source  

https://github.com/datocms/js-datocms-client/blob/ba0562aa8d61f61a9a78cd5734a34688a90e3d53/src/wpImport/schema/fields/text.js#L7

**Comment by matjack1** [comment]
yes @tbrannam you are right, it's a misspelling! We need to change this around I guess
