### ISSUE TITLE
Slug field not autogenerating when using client.createItems

### ISSUE THREAD

**Issue by wirsing** [datocms/js-datocms-client#61]
Steps to reproduce:

- Create model with Title and Slug field (slug being unique and dependent on title)
- Upload record with client.createItems

Observer Behavior:
- Client won't let me upload unless I specify slug field key
- If specified with null or else slug field is not autogenerated based on title

Expected Behavior:
- Client let's me upload without specifying slug field
- Slug field is autogenerated.

**Comment by matjack1** [comment]
Hello @wirsing this is the intended way it should work actually.

You should specify the slug field yourself when using the JS client or when updating content via the API.

**Comment by wirsing** [comment]
Thanks @matjack1 

That's a bummer :) How would I solve the following use case? 

I have to import roughly 1000 records from another service. Each record needs a slug since it contains all the data for a detail page. I don't want to manually generate slug for each one.

**Comment by stefanoverna** [comment]
You can just use something like https://www.npmjs.com/package/slugify to generate them, should be pretty straight-forward @wirsing!

**Comment by wirsing** [comment]
@stefanoverna I should have formulated better: How do I leverage the unique field + automated slug field functionality of dato when syncing around 1000 records without having to write my own duplicate slug + generate unique slug functions? I guess it's not possible with Dato?

**Comment by stefanoverna** [comment]
@wirsing I've got 2 options for you:

1. try to create the resource, and if it fails with a validation error on the slug then add an incremental integer to it
2. use https://github.com/Flet/github-slugger to generate slug: it handles duplicates for you client side
