### ISSUE TITLE
Some retry logic on api requests

### ISSUE THREAD

**Issue by fatihky** [datocms/js-datocms-client#70]
Hi, I am using [gatsby-source-datocms](https://github.com/datocms/gatsby-source-datocms) module. I get some connection errors from your module. My internet connection became unstable and I think my modem could cause this but I'm not sure. Anyways, my internet connections is unstable and I am getting this error very frequently:
```
  FetchError: request to https://site-api.datocms.com/site?include=item_types%2Citem_types  .fields failed, reason: Client network socket disconnected before secure TLS connection   was established
```
I also encounter with `Could not subscribe to real-time events!` error, which seems to come from here (**pusher** integration): https://github.com/datocms/js-datocms-client/blob/d9c360186adb5eb4896a42f79b73bc2cf05b159a/src/utils/subscribeToChannel.js#L39

So is it possible to add some retry logic to both api requests and pusher connections? I just wanted to discuss this first and if it's OK for you, I'd happily try to make a PR.

Thanks.

**Comment by fatihky** [comment]
Update: I've implemented retry logic for the API requests. You can check out it from here: https://github.com/fatihky/js-datocms-client/tree/feat/retry-api-requests
But I've not yet implemented the same thing for **pusher** integration.

**Comment by souljuse** [comment]
Retry logic is implemented in the latest releases of the client. Could you upgrade and tell us if you are still having this issue? Closing the issue in the meantime, feel free to re-open.
