### ISSUE TITLE
client.items.all() reads all model data and ignores user role

### ISSUE THREAD

**Issue by tomswork** [datocms/js-datocms-client#74]
Specifically relating to this function 
https://www.datocms.com/docs/content-management-api/resources/item/instances
When not using a filter and just calling `all()` it'll ignore the user role associated to the API key and list everything out, other functions like find() seem to be using the user role as expected

**Comment by matjack1** [comment]
thank you very much for this @tomswork

**Comment by matjack1** [comment]
I'm going to get back to you on Community: https://community.datocms.com/t/api-limitations-set-by-user-roles/1084/ as this is not a specific error of the JS client
