### ISSUE TITLE
Large file uploads via Cloud functions

### ISSUE THREAD

**Issue by gboston** [datocms/js-datocms-client#75]
It seems that the current implementation of the file upload with an url downloads the file locally before uploading it via the CMA. Is there a possibility to make use of streams or just an url instead of the current logic of downloading the file? This is giving me out of memory exceptions on Google Cloud functions of 2Gb memory.

**Comment by delphaber** [comment]
Related discussion: https://community.datocms.com/t/file-upload-from-cloud-functions/1101/2

**Comment by matjack1** [comment]
I'm closing this as we'll keep only the feature request on community, thanks for this!
