### ISSUE TITLE
Add command to destroy sandbox environment

### ISSUE THREAD

**Issue by RamonGebben** [datocms/js-datocms-client#79]
While setting up our CI process to create sandbox environments for each of our MR's(Merge Requests), I noticed there was no way to remove/destroy the sandbox when the MR gets merged/closed.

By adding a simple command which calls the `environments.destroy` method of JS client we can easily destroy sandboxes using the same tool by which is was created.

## API suggestion

```bash
dato environment destroy <environmentId>
```

**Comment by stefanoverna** [comment]
Awesome @RamonGebben, thanks! On it!
