### ISSUE TITLE
Add command to create a new project

### ISSUE THREAD

**Issue by RamonGebben** [datocms/js-datocms-client#81]
We would like to make project creation a part of our scaffolding process so it would be great if we could automate this.
I’ve been looking through the documentation but it seems like all API documentation already expects a project to exist.

## API proposal 

```bash
dato new site --name=<name> --plan=<plan>
```
> This will assume billing is setup and verified otherwise I expect the command to fail with an error "Payment not setup yet"

**Comment by souljuse** [comment]
Hi @RamonGebben this sounds more like a feature request than an issue :) We decided to collect all feature requests in one place, which is our[ community forum](https://community.datocms.com/c/feature-requests), and then release the most voted ones. It would be great to hear your voice there :D
