### ISSUE TITLE
Environment destroy command never receives `environmentId`

### ISSUE THREAD

**Issue by RamonGebben** [datocms/js-datocms-client#82]
While working with the new command `dato environment destroy` I noticed it always fails because the `environmentId` is improperly destructured from the options.

We need to use `<environmentId>` instead of `environmentId`.

**Comment by stefanoverna** [comment]
Could you provide a quick fix? 👍

**Comment by stefanoverna** [comment]
too fast!

**Comment by stefanoverna** [comment]
Released in 3.0.37
