### ISSUE TITLE
Issue with dato dump in v3.0.41

### ISSUE THREAD

**Issue by nadeemc** [datocms/js-datocms-client#88]
Running in nodejs v10, v12, or v14, v3.0.41 of the cli produces the following message on CentOS:

`/usr/bin/env: node --async-stack-traces: No such file or directory`

Workaround is to install v3.0.39 instead:

`npm i datocms-client@3.0.39 -g`

**Comment by stefanoverna** [comment]
Fixed in 3.0.42, thanks for reporting!
